name: Build Android Test APK

on:
  workflow_dispatch: # Murni hanya berjalan jika diklik manual dari tab Actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Inject Firebase Key, Config, & Diet Bahasa
        run: |
          # 1. Cari lokasi file build.gradle secara otomatis
          GRADLE_FILE=$(find . -type f \( -name "build.gradle" -o -name "build.gradle.kts" \) | grep "android/app" | head -n 1)
          if [ -z "$GRADLE_FILE" ]; then echo "ERROR: File build.gradle tidak ditemukan!"; exit 1; fi
          
          # 2. Suntikkan kunci rahasia Firebase yang asli
          APP_DIR=$(dirname "$GRADLE_FILE")
          echo '${{ secrets.FIREBASE_JSON }}' > "$APP_DIR/google-services.json"
          
          # 3. Ubah Package ID sistem internal ke com.desacluring.hub
          if [[ "$GRADLE_FILE" == *".kts" ]]; then
            sed -i 's/applicationId = ".*"/applicationId = "com.desacluring.hub"/g' "$GRADLE_FILE"
          else
            sed -i 's/applicationId ".*"/applicationId "com.desacluring.hub"/g' "$GRADLE_FILE"
          fi
          
          # 4. TRICK: Paksa Gradle menggunakan tanda tangan debug
          sed -i 's/signingConfigs.release/signingConfigs.debug/g' "$GRADLE_FILE"
          sed -i 's/signingConfigs.getByName("release")/signingConfigs.getByName("debug")/g' "$GRADLE_FILE"
          
          # 5. DIET BAHASA: Batasi hanya Bahasa Indonesia & Inggris untuk menyusutkan ukuran APK
          sed -i '/defaultConfig {/a \        resConfigs "en", "id"' "$GRADLE_FILE"
          
          # 6. SUNTIKAN UTAMA: Buat config.json untuk PUSH NOTIFIKASI & HARD-LOCK SERVER
          # Langkah ini sudah cukup, tidak perlu edit pubspec.yaml lagi!
          mkdir -p assets
          echo '{
            "push_gateway_url": "https://sygnal.desacluring.com",
            "default_homeserver": "https://hub.desacluring.com"
          }' > assets/config.json
          
          # 7. Ambil dependensi Flutter
          flutter pub get

      - name: Build APK Release (Langsing Khusus HP Modern + Kompresi)
        run: flutter build apk --release --target-platform android-arm64 --no-tree-shake-icons --obfuscate --split-debug-info=build/app/outputs/symbols

      - name: Upload APK Result
        uses: actions/upload-artifact@v4
        with:
          name: desacluring-chat-test
          path: build/app/outputs/flutter-apk/*.apk
